// <auto-generated />
namespace JabbR.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-alpha1-20818")]
    public sealed partial class RoomImages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoomImages));
        
        string IMigrationMetadata.Id
        {
            get { return "201310071935409_RoomImages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
